name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  checker:
    name: clippy, fmt, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1.4.0
      - name: install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: clippy
        run: cargo clippy --all --all-targets
      - name: fmt
        run: cargo fmt --all -- --check
      - name: build
        run: cargo build --verbose
